# Generated by Django 5.0.1 on 2024-02-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('Depart', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=30)),
                ('PHONE', models.CharField(default=None, max_length=30)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
